### ISSUE TITLE
Nested test command should be able to be a list, like a top-level command

### ISSUE THREAD

**Issue by jonpugh** [provision-ops/yaml-tests#4]
```
test:
  - phpunit
```
is valid.

```
test:
  command: phpunit
  description: PHPUnit Tests
```
is also valid, but...

```
test:
  description: PHPUnit Tests
  command:
    - phpunit
```
is not.
